fix(mypy): Typing related fixes
amora/visualization.py:18: error: Incompatible types in assignment (expression
24
has type "Callable[[DataFrame], Series[Any]]", variable has type
25
Generated HTML report (via XSLT): /home/runner/work/amora-data-build-tool/amora-data-build-tool/.mypy_coverage/index.html
26
"Callable[[DataFrame], str]")
27
        x_func: Callable[[pd.DataFrame], str] = lambda data: data["x"]
28
                                                ^
29
amora/visualization.py:18: error: Incompatible return value type (got
30
"Series[Any]", expected "str")
31
        x_func: Callable[[pd.DataFrame], str] = lambda data: data["x"]
32
                                                             ^
33
amora/visualization.py:19: error: Incompatible types in assignment (expression
34
has type "Callable[[DataFrame], Series[Any]]", variable has type
35
"Callable[[DataFrame], str]")
36
        y_func: Callable[[pd.DataFrame], str] = lambda data: data["y"]
37
                                                ^
38
amora/visualization.py:19: error: Incompatible return value type (got
39
"Series[Any]", expected "str")
40
        y_func: Callable[[pd.DataFrame], str] = lambda data: data["y"]
41
                                                             ^
42
amora/visualization.py:23: error: Incompatible types in assignment (expression
43
has type "Callable[[DataFrame], Series[Any]]", variable has type
44
"Callable[[DataFrame], str]")
45
        x_func: Callable[[pd.DataFrame], str] = lambda data: data["x"]
46
                                                ^
47
amora/visualization.py:23: error: Incompatible return value type (got
48
"Series[Any]", expected "str")
49
        x_func: Callable[[pd.DataFrame], str] = lambda data: data["x"]
50
                                                             ^
51
amora/visualization.py:24: error: Incompatible types in assignment (expression
52
has type "Callable[[DataFrame], Series[Any]]", variable has type
53
"Callable[[DataFrame], str]")
54
        y_func: Callable[[pd.DataFrame], str] = lambda data: data["y"]
55
                                                ^
56
amora/visualization.py:24: error: Incompatible return value type (got
57
"Series[Any]", expected "str")
58
        y_func: Callable[[pd.DataFrame], str] = lambda data: data["y"]
59
                                                             ^
60
amora/models.py:121: error: Argument "default_factory" to "field" has
61
incompatible type "Type[List[Any]]"; expected
62
"Callable[[], Set[Union[Label, str]]]"
63
        labels: Labels = field(default_factory=list)
64
                                               ^
65
amora/models.py:303: error: Unpacking a string is disallowed
66
            for (k, v) in model.__model_config__.labels:
67
            ^
68
amora/dash/components/model_labels.py:12: error: "Set[Union[Label, str]]" has
69
no attribute "items"
70
                for key, value in model.__model_config__.labels.items()
71
                                  ^
72
amora/questions.py:93: error: Incompatible types in assignment (expression has
73
type "VisualizationConfig", variable has type "Table")
74
                self.view_config = view_config
75
                                   ^
76
amora/dashboards.py:18: error: Incompatible types in assignment (expression has
77
type "date", base class "Filter" defined the type as "str")
78
        default: date = date.today()
79
                        ^
80
amora/dashboards.py:27: error: Incompatible types in assignment (expression has
81
type "Optional[str]", base class "Filter" defined the type as "str")
82
        default: Optional[str] = None
83
                                 ^
84
amora/dash/components/question_details.py:13: error: Invalid self argument
85
"BigNumber" to attribute function "value_func" with type
86
"Callable[[DataFrame], str]"
87
            big_number = view_config.value_func(visualization.data)
88
                         ^
89
amora/dash/components/question_details.py:13: error: Too many arguments
90
            big_number = view_config.value_func(visualization.data)
91
                         ^
92
amora/dash/components/question_details.py:19: error: Invalid self argument
93
"LineChart" to attribute function "x_func" with type
94
"Callable[[DataFrame], str]"
95
                    x=view_config.x_func(visualization.data),
96
                      ^
97
amora/dash/components/question_details.py:19: error: Too many arguments
98
                    x=view_config.x_func(visualization.data),
99
                      ^
100
amora/dash/components/question_details.py:20: error: Invalid self argument
101
"LineChart" to attribute function "y_func" with type
102
"Callable[[DataFrame], str]"
103
                    y=view_config.y_func(visualization.data),
104
                      ^
105
amora/dash/components/question_details.py:20: error: Too many arguments
106
                    y=view_config.y_func(visualization.data),
107
                      ^
108
amora/dash/pages/dashboard.py:7: error: Module "amora.dash.components.filters"
109
has no attribute "filter"
110
    from amora.dash.components.filters import filter
111
    ^
112
amora/dash/pages/dashboard.py:70: error: Argument 1 to "render" has
113
incompatible type "Optional[Any]"; expected "Dashboard"
114
        component = render(dashboard)
115
                           ^
116
amora/dash/components/filters/filter.py:3: error: Module
117
"amora.dash.components.filters" has no attribute "accepted_values_filter"
118
    from amora.dash.components.filters import accepted_values_filter, date...
119
    ^
120
amora/dash/components/filters/filter.py:3: error: Module
121
"amora.dash.components.filters" has no attribute "date_filter"
122
    from amora.dash.components.filters import accepted_values_filter, date...
123
    ^
124
Generated XML report: /home/runner/work/amora-data-build-tool/amora-data-build-tool/.mypy_coverage/index.xml
125
Installing missing stub packages:
126
/opt/hostedtoolcache/Python/3.9.13/x64/bin/python -m pip install types-protobuf types-setuptools types-typed-ast
127

128

129
Generated HTML report (via XSLT): /home/runner/work/amora-data-build-tool/amora-data-build-tool/.mypy_coverage/index.html
130
Generated XML report: /home/runner/work/amora-data-build-tool/amora-data-build-tool/.mypy_coverage/index.xml
131
Found 24 errors in 8 files (checked 71 source files)